/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MenteeService } from "../mentee.service";
import { MenteeCreateInput } from "./MenteeCreateInput";
import { Mentee } from "./Mentee";
import { MenteeFindManyArgs } from "./MenteeFindManyArgs";
import { MenteeWhereUniqueInput } from "./MenteeWhereUniqueInput";
import { MenteeUpdateInput } from "./MenteeUpdateInput";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { SessionWhereUniqueInput } from "../../session/base/SessionWhereUniqueInput";

export class MenteeControllerBase {
  constructor(protected readonly service: MenteeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mentee })
  async createMentee(@common.Body() data: MenteeCreateInput): Promise<Mentee> {
    return await this.service.createMentee({
      data: data,
      select: {
        age: true,
        createdAt: true,
        id: true,
        name: true,
        preferences: true,
        skills: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Mentee] })
  @ApiNestedQuery(MenteeFindManyArgs)
  async mentees(@common.Req() request: Request): Promise<Mentee[]> {
    const args = plainToClass(MenteeFindManyArgs, request.query);
    return this.service.mentees({
      ...args,
      select: {
        age: true,
        createdAt: true,
        id: true,
        name: true,
        preferences: true,
        skills: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mentee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mentee(
    @common.Param() params: MenteeWhereUniqueInput
  ): Promise<Mentee | null> {
    const result = await this.service.mentee({
      where: params,
      select: {
        age: true,
        createdAt: true,
        id: true,
        name: true,
        preferences: true,
        skills: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mentee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMentee(
    @common.Param() params: MenteeWhereUniqueInput,
    @common.Body() data: MenteeUpdateInput
  ): Promise<Mentee | null> {
    try {
      return await this.service.updateMentee({
        where: params,
        data: data,
        select: {
          age: true,
          createdAt: true,
          id: true,
          name: true,
          preferences: true,
          skills: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mentee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMentee(
    @common.Param() params: MenteeWhereUniqueInput
  ): Promise<Mentee | null> {
    try {
      return await this.service.deleteMentee({
        where: params,
        select: {
          age: true,
          createdAt: true,
          id: true,
          name: true,
          preferences: true,
          skills: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/sessions")
  @ApiNestedQuery(SessionFindManyArgs)
  async findSessions(
    @common.Req() request: Request,
    @common.Param() params: MenteeWhereUniqueInput
  ): Promise<Session[]> {
    const query = plainToClass(SessionFindManyArgs, request.query);
    const results = await this.service.findSessions(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        duration: true,
        id: true,

        mentee: {
          select: {
            id: true,
          },
        },

        mentor: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sessions")
  async connectSessions(
    @common.Param() params: MenteeWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        connect: body,
      },
    };
    await this.service.updateMentee({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sessions")
  async updateSessions(
    @common.Param() params: MenteeWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        set: body,
      },
    };
    await this.service.updateMentee({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sessions")
  async disconnectSessions(
    @common.Param() params: MenteeWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        disconnect: body,
      },
    };
    await this.service.updateMentee({
      where: params,
      data,
      select: { id: true },
    });
  }
}
